# Generated by Django 6.0.3 on 2026-03-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digilib_core', '0003_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='digilib_core.tag'),
        ),
    ]
