# Generated by Django 6.0.3 on 2026-04-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digilib_core', '0004_book_tags'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('available_copies__lte', models.F('total_copies'))), name='check_available_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('available_copies__gte', 0), ('total_copies__gte', 0)), name='check_positive_copies'),
        ),
    ]
