# Generated by Django 6.0.3 on 2026-04-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digilib_core', '0005_book_check_available_lte_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ nhận sách'), ('borrowed', 'Đang mượn'), ('returned', 'Đã trả'), ('overdue', 'Quá hạn'), ('cancelled', 'Đã hủy')], default='borrowed', max_length=20),
        ),
    ]
